### ISSUE TITLE
Examples are wrong | Patterns are not relative

### ISSUE THREAD

**Issue by janAkali** [zendbit/nim_nwatchdog#2]
Tested with Nim 1.6, 2.0, 2.1

Example doesn't work because program expects full path as pattern:

Now (doesn't detect any events):
```
wd.add(
  "/home/zendbit/test/jscript",
  "[\\w\\W]*\\.[(txt)|(js)]",
  ...
```

If we change example like this - everything works:
```
wd.add(
  "/home/zendbit/test/jscript",
  "/home/zendbit/test/jscript/[\\w\\W]*\\.[(txt)|(js)]",
  ...
```

It's easy to fix, but I'm not sure what's the expected behavior, hence the weird title for issue:

- We could update Readme to use full path as a pattern.

- Or add a `relative` flag to `walkDirRec` iterator to make examples valid:
https://github.com/Archargelod/nim_nwatchdog/blob/4e037cbcc7d9786534dee2d1c31a3cd525cfa345/nwatchdog.nim#L93

I can write a Pull Request, if you tell me which one =)

**Comment by zendbit** [comment]
Hi sorry for the wrong pattern, I already fix the issue in the README.md and you can refer to it.

I input the wrong pattern on regex :-) thanks for the report.

```nim
wd.add(
  "/home/zendbit/test/jscript",
  "[\\w\\W]*\\.[(txt)|(js)]+$", ## change this from previous pattern "[\\w\\W]*\\.[(txt)|(js)]"
  (proc (file: string, evt: NWatchEvent, param: string) {.gcsafe async.} =
    echo param
    case evt
    of Created:
      echo file & " " & $evt
    of Modified:
      echo file & " " & $evt
    of Deleted:
      echo file & " " & $evt),
  "this param will pass to the event callback watch js and txt")
```

**Comment by zendbit** [comment]
let me know if you have other issue

**Comment by zendbit** [comment]
let me know if you have any other problems, and you're free to do a code review :-)

**Comment by janAkali** [comment]
Thank you for quick response.

> let me know if you have any other problems

Now the example program constantly says that the file is deleted when it's still there.
I believe [this line](https://github.com/zendbit/nim_nwatchdog/blob/69651156ee7f70b90ee21ba7da5175877ea41b77/nwatchdog.nim#L181) should be:
```nim
if not snapCmpContent.contains(re2 &"{snapInfo[0]}\\|\\|[\\w\\W]+?[\n]+"):
```

**Comment by zendbit** [comment]
Hi,

thanks for your considerations, I already merge your pattern matching with contains https://github.com/zendbit/nim_nwatchdog/commit/7d58a1e704e2b7b6a25bf180b9f47b4ce485a944

any problems, you can fork and pull request or submit the issue

also I update release to version 0.2.2

many thanks.
